name: Docker

on:
  workflow_dispatch: {}
  # schedule:
  #   - cron: "0 16 * * 1"
  push:
    branches:
      - main
    paths:
      - Dockerfile
      - crowdin_script.sh
      - crowdin-action/**
  pull_request:
    paths:
      - Dockerfile

concurrency: 
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  docker:
    name: docker build
    uses: Docker-Collection/reusable-workflows/.github/workflows/docker-build.yml@main
    with:
      docker_name: "ghcr.io/docker-collection/crowdin-cli"
      docker_label_author: "Efina"
      docker_label_title: "Docker Crowdin CLI"
      docker_label_description: "Crowdin CLI, MultiArch"
      version_detecter: true
      version_detecter_var: "CROWDIN_VERSION="

  docker_action:
    name: docker build (action)
    needs: [ "docker" ]
    uses: Docker-Collection/reusable-workflows/.github/workflows/docker-build.yml@main
    with:
      docker_name: "ghcr.io/docker-collection/crowdin-action"
      context: "crowdin-action/"
      dockerfile: "crowdin-action/Dockerfile"
      docker_label_author: "Efina"
      docker_label_title: "Docker Crowdin CLI Action"
      docker_label_description: "Crowdin CLI, MultiArch"
